//
// Created by Michał Zmyślony on 27/10/2023.
//

#ifndef VECTOR_SLICER_DISAGREEMENT_FUNCTION_CONFIG_H
#define VECTOR_SLICER_DISAGREEMENT_FUNCTION_CONFIG_H


class DisagreementFunctionConfig {

};


#endif //VECTOR_SLICER_DISAGREEMENT_FUNCTION_CONFIG_H
